### ISSUE TITLE
gnome-mpv can't installl under ubuntu 14.04

### ISSUE THREAD

**Issue by sbw983** [gnome-mpv/gnome-mpv#77] opened 2015-11-08 15:03 UTC
hello
i use ubuntu 14.04 and libgtk3 for my system is just 3.10, i can't install the last gnome-mpv on my ubuntu 14.04(neither from source or via ppa), so can u downgrade  gtk3 to 3.10? thank you. gnome-mpv is the best ui for mpv and i use it from v0.1 to v0.5 but now maybe i have to say bye to it.

BTW: if u can add audio and subtitle channel selection function? i got a movi name Twelve O'Clock High 1949 BDRip 1080p DTS HighCode- PublicHash.mkv and it have 26 subtitles. it make me crazy to find the correct subtitle for me, and at last i give up to use mpv and just back to smplayer, smplayer have a function for select subtitles, i hope gnome-mpv could get this function soon.

**Comment by sbw983** [comment] 2015-11-08 15:14
another issue
when play on fullscreen mode, gnome-mpv can't hide top bar.

**Comment by gnome-mpv** [comment] 2015-11-09 20:29
>i use ubuntu 14.04 and libgtk3 for my system is just 3.10, i can't install the last gnome-mpv on my ubuntu 14.04(neither from source or via ppa), so can u downgrade gtk3 to 3.10? thank you. gnome-mpv is the best ui for mpv and i use it from v0.1 to v0.5 but now maybe i have to say bye to it.

I just pushed a new commit (a2f09af) that adds a new autoconf option (--disable-opengl-cb) for disabling opengl-cb support. Disabling opengl-cb allows building with gtk+ >= 3.14. You can get gtk+ 3.14 for Ubuntu 14.04 from [this ppa](https://launchpad.net/~ricotz/+archive/ubuntu/testing).

>BTW: if u can add audio and subtitle channel selection function? i got a movi name Twelve O'Clock High 1949 BDRip 1080p DTS HighCode- PublicHash.mkv and it have 26 subtitles. it make me crazy to find the correct subtitle for me, and at last i give up to use mpv and just back to smplayer, smplayer have a function for select subtitles, i hope gnome-mpv could get this function soon.

That's doable. Please open a new issue for this.

>when play on fullscreen mode, gnome-mpv can't hide top bar.

I can't reproduce this. It might have already been fixed in the latest git version.

**Comment by gnome-mpv** [comment] 2015-12-09 07:17
Track selection has been implemented in eaef235.

**Closed by gnome-mpv** 2015-12-09 07:17 UTC
