### ISSUE TITLE
VA-API doesn’t work with Flatpak

### ISSUE THREAD

**Issue by jurf** [gnome-mpv/gnome-mpv#253] opened 2017-02-11 17:13 UTC
When running GNOME MPV from a Flatpak installation and trying to use VA-API it fails to load it. I get this output:
```
❯ flatpak run io.github.GnomeMpv                                         
libva info: VA-API version 0.38.1
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/dri/i965_drv_video.so
libva info: va_openDriver() returns -1
```

This is the output with regular MPV and working VA-API:
```
❯ mpv '/home/juraj/Video/HDD-Filmy/bbb_sunflower_1080p_60fps_normal.mp4' 
Playing: /home/juraj/Video/HDD-Filmy/bbb_sunflower_1080p_60fps_normal.mp4
 (+) Video --vid=1 (*) (h264)
 (+) Audio --aid=1 --alang=und (*) (mp3)
     Audio --aid=2 --alang=und (*) (ac3)
File tags:
 Artist: Blender Foundation 2008, Janus Bager Kristensen 2013
 Comment: Creative Commons Attribution 3.0 - http://bbb3d.renderfarming.net
 Composer: Sacha Goedegebure
 Genre: Animation
 Title: Big Buck Bunny, Sunflower version
libva info: VA-API version 0.39.4
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_0_39
libva info: va_openDriver() returns 0
AO: [pulse] 48000Hz stereo 2ch s16
Using hardware decoding (vaapi).
VO: [opengl] 1920x1080 vaapi
```

This is the output of `vainfo`:
```
❯ vainfo
libva info: VA-API version 0.39.4
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_0_39
libva info: va_openDriver() returns 0
vainfo: VA-API version: 0.39 (libva 1.7.3)
vainfo: Driver version: Intel i965 driver for Intel(R) Sandybridge Mobile - 1.7.3
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointEncSlice
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointEncSlice
      VAProfileH264StereoHigh         :	VAEntrypointVLD
      VAProfileVC1Simple              :	VAEntrypointVLD
      VAProfileVC1Main                :	VAEntrypointVLD
      VAProfileVC1Advanced            :	VAEntrypointVLD
      VAProfileNone                   :	VAEntrypointVideoProc
```

**Comment by TingPing** [comment] 2017-02-11 17:18
I believe this is an issue better discussed over at https://github.com/flatpak/flatpak

**Comment by DoctorJellyface** [comment] 2017-02-11 18:06
Hm, I’ll try reporting it there then.

However, to make use of this moment, is GNOME MPV’s inability to open a file from say Files a known issue?

**Comment by TingPing** [comment] 2017-02-11 18:19
> However, to make use of this moment, is GNOME MPV’s inability to open a file from say Files a known issue?

I can reproduce that and will look into it. Using the open dialog from within the application should still work fine though. (assuming `xdg-desktop-portal-gtk` is installed).

**Comment by DoctorJellyface** [comment] 2017-02-11 18:21
Yes I tried that, but since I open video files exclusively from Files it’s a showstopper for me.

**Comment by TingPing** [comment] 2017-02-11 18:22
I remember it working at some point so might be a regression.

**Comment by gnome-mpv** [comment] 2017-02-12 14:27
@TingPing: It doesn't work outside of flatpak either. Looks like it's a regression caused by 11067bc05ed17965d2ac439c36850faf0f38a37c.

**Comment by TingPing** [comment] 2017-06-20 16:24
This can probably be closed as the upstream issue is here: https://github.com/flatpak/flatpak/issues/4

**Closed** 2017-06-21 13:44 UTC
Labels: not our bug

**Comment by TingPing** [comment] 2017-06-26 17:31
Just as another update, the Intel VAAPI driver should land soon: https://github.com/flatpak/freedesktop-sdk-images/pull/29

**Comment by hubslave** [comment] 2017-08-28 19:22
Very happy to see that VAAPI is going to be supported :) just another small finding: Flatpak apps are also unable to use nvidia decoder, OpenCL acceleration and vdpau - output from GnomeMpv flatpak:
...
Failed to open VDPAU backend libvdpau_i965.so: cannot open shared object file: No such file or directory
...
** Message: [ffmpeg] Cannot load libnvcuvid.so.1
** Message: [ffmpeg/video] h264_cuvid: Failed loading nvcuvid.
...

**Comment by TingPing** [comment] 2017-08-28 23:58
@hubslave Please search for and open these types of issues on flatpak/flatpak. AFAIK there is an issue for vdpau already.

**Comment by hubslave** [comment] 2017-09-11 20:25
@TingPing I found out that I had problems with my GPU drivers, CUDA seems to be working now. But OpenCL and VDPAU still do not work. When trying to run GnomeMPV with VDPAU hardware acceleration it crashes whole program. But hardware decoding with CUDA seems working fine.

**Comment by TingPing** [comment] 2017-09-22 07:25
This is now packaged btw: https://github.com/flathub/org.freedesktop.Platform.VAAPI.Intel

**Comment by hubslave** [comment] 2017-09-23 15:12
Great, thank you very much @TingPing! :)
