### ISSUE TITLE
Cannot start GnomeMpv flatpak after Nvidia driver update

### ISSUE THREAD

**Issue by hubslave** [gnome-mpv/gnome-mpv#310] opened 2017-09-23 16:31 UTC
**Overview Description:**
Hello, today I updated nvidia drivers from 384-69 to 384-90 and since then I cannot start GnomeMpv flatpak.

Here is the command I try to run and output I get:

```
$ flatpak run io.github.GnomeMpv
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
libEGL warning: DRI2: failed to authenticate
: CommandLine Error: Option 'bb-vectorize-ignore-target-info' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options
```

I am not sure what is the issue but I suspect that this problem occurs since there are no available flatpak runtimes for Nvidia 384-90 drivers and therefore the Nvidia flatpak runtime is incompatible with my current drivers? Is this expected behaviour in this situation or could there be some other problem?

**Steps to Reproduce:**
1. Update Nvidia drivers to 384-90
2. Try to start GnomeMpv flatpak
3. Get errors

**Actual Results:**
GnomeMpv does not run

**Expected Results:**
GnomeMpv runs :)

**Version:**
Latest Stable

**Additional Information:**
Enterprise Linux 7.4, Flatpak ver. 0.8.7

Have a nice day :)

**Comment by TingPing** [comment] 2017-09-23 22:24
The Flatpak drivers just haven't been updated and you'll have to wait a bit.

**Comment by hubslave** [comment] 2017-09-24 11:40
Thank you @TingPing for explanation. Its ok, I'm not in a hurry, I just wanted to know if it's expected behavior in this case :) I'm curious how these GL Runtimes in flatpaks work, they pack the whole nvidia driver or "just provide" something like "portal" to already installed drivers?

**Comment by TingPing** [comment] 2017-09-24 12:06
Flatpak uses your kernel so that is where part of the nvidia driver is, the problem is the libgl implementation is the other half and must match the exact version of the kernel. Flatpak can't just pull in host libraries as well, who knows what the hell those link to, so it must package them itself.

This may change in the future because it is a hassle to deal with though.

**Comment by hubslave** [comment] 2017-09-26 01:20
Thank you very much. Now I think I understand why does it work this way :) So if flatpak used external system library which links to some malicious code it could also attack whole flatpak sandbox...? Does not NVidia use something like digital signing of their libraries? Could not flatpak check those signing keys and decide if they are ok or not and depending on their "credibility" use them instead of runtimes? (To be honest I am not an expert in this field, I'm just interested in flatpaks and writing ideas which come to my mind :) ) Have a nice day

**Comment by TingPing** [comment] 2017-09-26 02:11
It isn't really about malicious code it is more about how libraries and ABIs work. You cannot mix and match random binaries and expect them to work.

**Comment by TingPing** [comment] 2017-10-07 20:29
You can close this issue.

**Closed** 2017-10-08 01:22 UTC
Labels: flatpak
