### ISSUE TITLE
Flatpak - Playlist doesn't work

### ISSUE THREAD

**Issue by ivandotv** [gnome-mpv/gnome-mpv#411] opened 2019-01-17 20:56 UTC
Overview Description:

Playlist functionality is broken.

Steps to Reproduce:
1. Open one file with player by double clicking on the file.
2. Drag another more file to the playlist.
3. Click to play the second file or what for the first file to finish, results are the same.

Actual Results:
Player can't play any other file from the playlist other than the initial file.
Error: `Playback was terminated abnormally. Reason: loading failed.`

Expected Results:
Play all files in the playlist

Version: `0.15`

Additional Information:
I have noticed that the first file location ( when using `copy file location` option from the menu) is something like: `/run/user/1000/doc/ad68291b/movie-1.mp4`

But the second file in the playlist has this location: `/home/userName/Downloads/movie-2.mp4`
And that is the actual location of the file.

Also if I first open the player and then drag the files to the playlist, then I can't play any of the files, and I get back the same error.

**Comment by TingPing** [comment] 2019-01-17 22:48
Duplicate of #300

**Closed** 2019-01-18 08:40 UTC
Labels: flatpak, not our bug

**Comment by ivandotv** [comment] 2019-01-18 17:18
I don't know how this functionality is similar to lets say VLC player but that player via flatpak doesn't have this problem.

**Comment by TingPing** [comment] 2019-01-18 21:33
The VLC package disables more sandboxing. The GNOME-MPV Flatpak is actually quite secure. You can do `flatpak override --user --filesystem=host io.github.GnomeMpv` if you trust your media.

**Comment by ivandotv** [comment] 2019-01-18 21:38
I have just tried it and it works. Thanks.
Btw, I trust my media but I don't trust my media :dagger:

**Comment by ivandotv** [comment] 2019-12-09 17:55
Since the name change this is the proper command:
`flatpak override --user --filesystem=host io.github.celluloid_player.Celluloid`
